@startumlnname "Generic Use Case - IO Channel - Option B"
left to right direction

!include generic-use-case.puml

title "Generic Use Case - IO Channel - Option B"

hide DefaultRequest
hide DefaultResponse
hide Kernel

package "IO Channel" {
    class IOChannelController

    IOChannelController --* ChannelRequest
    IOChannelController --* ChannelResponse

    ChannelRequest <|-- RequestBoundary
    ChannelResponse <|-- ResponseBoundary

}

@enduml